name: Coding Heatmap

on:
  schedule:
    - cron: "0 0 * * *" # Runs every midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate Heatmap
    steps:
      - uses: actions/checkout@v3
      - name: Hackatime Heatmap
        uses: ImShyMike/hackatime-heatmap@master
        with:
          api_key: ${{ secrets.WAKATIME_API_KEY }}