name: Coding Heatmap

on:
  schedule:
    - cron: "0 0 * * *" # Runs every midnight
  workflow_dispatch:      # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate Heatmap
    
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v3
      - name: Hackatime Heatmap
        uses: ImShyMike/hackatime-heatmap@master
        with:
          api_key: ${{ secrets.WAKATIME_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}